### ISSUE TITLE
Make a list of all time series colonies available at every time point with good RNA and DNA

### ISSUE THREAD

**Issue by hputnam** [urol-e5/timeseries#48]
These would be to make the decisions on the molecular samples still on the skeleton for histone modification that would be processed by FIU.

**Comment by hputnam** [comment]
https://docs.google.com/spreadsheets/d/1A764av1a3VORX6m9aDUEcoY9Bx9l0fvGtV5ycm2J9Wo/edit#gid=0

https://github.com/urol-e5/timeseries/blob/master/timepoint_1/1_corals_sampled.csv

https://github.com/urol-e5/timeseries/blob/master/timepoint_2/2_corals_sampled.csv

https://github.com/urol-e5/timeseries/blob/master/timepoint_3/3_corals_sampled.csv

https://github.com/urol-e5/timeseries/blob/master/timepoint_4/4_corals_sampled.csv

**Comment by AHuffmyer** [comment]
What is the format you would like this master list to be? Do you want it in the google sheet linked above or a new separate sheet?
