### ISSUE TITLE
Add Ik and Ic calculations to PI curve code

### ISSUE THREAD

**Issue by AHuffmyer** [urol-e5/timeseries#51]
Add code to calculate Ik and Ic to PI curve code.

**Comment by AHuffmyer** [comment]
Hey @ferdi-p! I have a question about this. We want to add calculations for Ik (light saturation point) and Ic (light compensation point) to our PI curve calculations. We used an nls curve fit to generate Am, AQY, and Rd values. Ik is calculated as Am / AQY. I believe that Ic (which is essentially the x intercept) can be calculated as Rd / AQY. Have you calculated these metrics before? Does this sound correct? I'm digging through the literature but the math is tough for me to decode :)

**Comment by ferdi-p** [comment]
Hi Ariana! Hmm I forgot the functional form  / the parameter names. Can you
remind me where to find the equations (or just the paper draft)?

**Comment by AHuffmyer** [comment]
I found some definitions in this paper here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8722371/

Our script for calculating curves and parameters is here: https://github.com/urol-e5/timeseries/blob/master/timepoint_1/scripts/pi_curves_nls_step2.Rmd

**Comment by ferdi-p** [comment]
ok yea that looks good. I sent you a Slack to be sure I remember the
function for the fits right.

**Comment by AHuffmyer** [comment]
Ferdi derived equations for our quadratic equation. Updated in each time point nls step 2 scripts.
