### ISSUE TITLE
NAs in data

### ISSUE THREAD

**Issue by jrcunning** [urol-e5/timeseries#55]
@AHuffmyer when I run the code in 1_assemble_data.Rmd, it produces a Summary_Responses.csv file that is modified from what's in the repository, and has a bunch of NAs in it... can you take a look?

**Comment by AHuffmyer** [comment]
Yes, looking now!

**Comment by AHuffmyer** [comment]
The script ran it for me just fine! I just pushed a revision that removed an unnecessary data column, but the values are all there, no NA's. I recommend restarting your R session and running all code chunks again. Sometimes there is an issue with masking in dplyr that prevents the `summarise` and `group_by` functions from working and therefore generating NAs. Let me know if that works!
