### ISSUE TITLE
Price metabolomics and lipidomics options

### ISSUE THREAD

**Issue by AHuffmyer** [urol-e5/timeseries#70]
# From UW 

For untargeted and lipid analysis, you would need to provide two separate sample specimens (if possible) since these two assays require totally different sample prep. Our prices per sample are

Quantitative Lipidomics: $99 MS runs + $27 tissue sample prep + $15 BCA protein assay (needed for data normalization) = $141 TOTAL per sample

Global (untargeted) LC-MS profiling: $112 for LC-MS runs + $27 tissue sample prep + $15 BCA protein assay (needed for data normalization) = $154 TOTAL per sample 

For 116 samples, the TOTAL price for both type of analyses would be $34,220. ($259 per sample total) 

# From Javi 

Quote was for $425 for both metabolomics and lipidomics per sample.

We need to decide if we want both metabolomics and lipidomics (I think we do) and where we want to send samples for processing. 

Will also need to decide on sample input. I suggest that we do host/symbiont separations and send host tissue sample for analysis.

**Comment by jarcasariego** [comment]
It seems that the high price is for a subset of samples that will allow the development of the protocol and after that the price will be lower. Chema and I are still figuring this out.
